version: '3'

services:
  db:
    build:
      context: db
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD --silent'
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net
    environment:
      - MYSQL_DATABASE=notifs
      - MYSQL_ROOT_PASSWORD
    expose:
      - 3306
      - 33060

  notifier:
    build:
      context: notifier
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=notifs
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - GMAIL_USERNAME
      - GMAIL_APP_PASSWORD

  scripts:
    build:
      context: scripts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=notifs
      - MYSQL_USER=root
      - MYSQL_PASSWORD

volumes:
  db-data:


networks:
  net:
